DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS trajectory;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE trajectory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  longtitude FLOAT NOT NULL,
  latitude FLOAT NOT NULL,
  timestamp TIMESTAMP NOT NULL
);